Add basic Managed Account docs
zincio/apidocs pull request #2
Opened 2017-08-22 21:53 UTC by lachesis

2017-08-22 22:13 UTC, wangjohn requested changes
Cool, thanks for adding this! We should include this somewhere in the docs, probably above "Object Reference" section, but below the "Get product details" section. To do that, go to `source/index.md` and put `addax` inside of the `includes` list near the top of the section between `products` and `object_reference`

2017-08-22 22:13 UTC, wangjohn commented on source/includes/_addax.md
> +below.
Should we put something in here to say that people should default to using "inaccurate website description" for US and whatever we use for UK?

2017-08-22 22:13 UTC, wangjohn commented on source/includes/_addax.md
> +support@zinc.io and provide your order ID.
We should note that this is best effort and doesn't always work.

2017-08-22 22:13 UTC, wangjohn commented on source/includes/_addax.md
> +## Funding your account
We should at some point differentiate between funding the account balance and the fee we charge for each order, which can be separate.

2017-08-23 22:46 UTC, lachesis commented
Fixed comments.

2017-08-23 22:46 UTC, lachesis commented on source/includes/_addax.md
> +## Funding your account
Did this

2017-08-23 22:53 UTC, merged